Ensemble Learning: Implement Random Forest Classifier model
to predict the safety of the car.

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import LabelEncoder 


In [4]:
df = pd.read_csv(r"F:\BE\My Cl1\CL1\m5\car_evaluation.csv")
df

Buying price Maintance cost No of doors No of persons lug_boot safety  \
0           vhigh          vhigh           2             2    small    low   
1           vhigh          vhigh           2             2    small    med   
2           vhigh          vhigh           2             2    small   high   
3           vhigh          vhigh           2             2      med    low   
4           vhigh          vhigh           2             2      med    med   
...           ...            ...         ...           ...      ...    ...   
1723          low            low       5more          more      med    med   
1724          low            low       5more          more      med   high   
1725          low            low       5more          more      big    low   
1726          low            low       5more          more      big    med   
1727          low            low       5more          more      big   high   

     Decision  
0       unacc  
1       unacc  
2       unacc  
3       unacc  
4       unacc  
...       ...  
1723     good  
1724    vgood  
1725    unacc  
1726     good  
1727    vgood  

[1728 rows x 7 columns]

In [5]:
df.describe()

Buying price Maintance cost No of doors No of persons lug_boot safety  \
count          1728           1728        1728          1728     1728   1728   
unique            4              4           4             3        3      3   
top           vhigh          vhigh           2             2    small    low   
freq            432            432         432           576      576    576   

       Decision  
count      1728  
unique        4  
top       unacc  
freq       1210

In [6]:
col_names = ['Buying' , 'maint' ,'doors' ,'persons' ,'lug_boot' ,'safety' ,'class']
df.columns = col_names

df.head()

Buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [7]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype != 'object':
        continue

    df[col] = le.fit_transform(df[col])


In [8]:
df.head()

Buying  maint  doors  persons  lug_boot  safety  class
0       3      3      0        0         2       1      2
1       3      3      0        0         2       2      2
2       3      3      0        0         2       0      2
3       3      3      0        0         1       1      2
4       3      3      0        0         1       2      2

In [9]:
X = df.drop(['class'],axis =1)
y = df['class']

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state=60)
X_train.shape , X_test.shape

((1382, 6), (346, 6))

In [10]:
rfc = RandomForestClassifier(n_estimators = 18+25)
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=43)

In [11]:
y_pred = rfc.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

print('Accuracy:',accuracy*100,'%','\n')
print('Confusion Matrix:\n',conf_matrix)

Accuracy: 96.53179190751445 % 

Confusion Matrix:
 [[ 78   1   8   1]
 [  1  11   0   0]
 [  1   0 230   0]
 [  0   0   0  15]]
